name: Atualizar clima de Alagoas
on:
  schedule:
    - cron: "*/05 * * * *"  # A cada 05 minutos
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10
      - name: Instalar dependências
        run: pip install requests
      - name: Gerar JSON
        env:
          API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
        run: |
          python gerar_clima_json.py
      - name: Commit e push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add clima_alagoas.json
          git commit -m "Atualização automática do clima"
          git push
