name: Atualizar Clima Alagoas

on:
  schedule:
    # A cada 2 minutos (GitHub Actions usa cron UTC)
    - cron: "*/2 * * * *"
  workflow_dispatch: # permite rodar manualmente

jobs:
  atualizar-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Gerar JSON de clima
      run: |
        python3 <<'EOF'
        import json
        import random

        cidades = ["Maceió", "Arapiraca", "Delmiro Gouveia", "Penedo"]
        dados = []

        for cidade in cidades:
            # Exemplo: gera temperatura aleatória e ícone fictício
            temp = random.randint(25, 32)
            icone = random.choice(["sol", "nublado", "chuva", "sol_nuvens"])
            dados.append({
                "nome": cidade,
                "temp": str(temp),
                "icone": icone
            })

        with open("clima_alagoas.json", "w", encoding="utf-8") as f:
            json.dump(dados, f, ensure_ascii=False, indent=2)
        EOF

    - name: Commitar e enviar para o GitHub
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add clima_alagoas.json
        git commit -m "Atualização automática do clima"
        git push
      continue-on-error: true  # evita erro se não houver mudanças
